require "Items/Distributions"
require 'Items/SuburbsDistributions'
require 'Items/ProceduralDistributions'
require 'Vehicles/VehicleDistributions'

-- Fire Extinguisher
table.insert(ProceduralDistributions["list"]["BarCounterWeapon"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["BarCounterWeapon"].items, 1);
table.insert(ProceduralDistributions["list"]["BreakRoomShelves"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["BreakRoomShelves"].items, 5);
table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, 4);
table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, 2);
table.insert(ProceduralDistributions["list"]["CarSupplyTools"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["CarSupplyTools"].items, 2);
table.insert(ProceduralDistributions["list"]["CrateAntiqueStove"].junk.items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["CrateAntiqueStove"].junk.items, 1);
table.insert(ProceduralDistributions["list"]["CrateCamping"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["CrateCamping"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateMechanics"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["CrateMechanics"].items, 1);
table.insert(ProceduralDistributions["list"]["CrateMetalwork"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["CrateMetalwork"].items, 4);
table.insert(ProceduralDistributions["list"]["EngineerTools"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["EngineerTools"].items, 2);
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["FactoryLockers"].items, 1);
table.insert(ProceduralDistributions["list"]["FireStorageTools"].junk.items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["FireStorageTools"].junk.items, 100);
table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, 1);
table.insert(ProceduralDistributions["list"]["GarageMechanics"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["GarageMechanics"].items, 0.5);
table.insert(ProceduralDistributions["list"]["GarageMetalwork"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["GarageMetalwork"].items, 2);
table.insert(ProceduralDistributions["list"]["GarageTools"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["GarageTools"].items, 2);
table.insert(ProceduralDistributions["list"]["GigamartTools"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["GigamartTools"].items, 2);
table.insert(ProceduralDistributions["list"]["JanitorMisc"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["JanitorMisc"].items, 4);
table.insert(ProceduralDistributions["list"]["JanitorTools"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["JanitorTools"].items, 7);
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 1);
table.insert(ProceduralDistributions["list"]["MechanicShelfMisc"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["MechanicShelfMisc"].items, 7);
table.insert(ProceduralDistributions["list"]["MetalShopTools"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["MetalShopTools"].items, 6);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCounter"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCounter"].items, 8);
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, "Base.Extinguisher");
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, 3);
